### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by wiese** [MicuEmerson/vue-piano#1]
Thank you for creating the initial version of vue-piano - I think it has a nice and clean setup, does one thing and well.

I'm considering to use the `PianoKeyboard` component as a building block of another application. Is there any chance that there will be a version supporting [vue 3](https://v3.vuejs.org/guide/migration/introduction.html)? There are a couple of features I'd like to suggest (and maybe PR) for the component, but it would be more fun if I then could use them myself (in a vue 3 context).

**Comment by MicuEmerson** [comment]
Thank you for being interested! Unfortunately, I don't have time to do the transition from vue 2 to vue 3. Maybe in the future when I will work again with javascript & vue.

**Comment by wiese** [comment]
Thanks for your response!
